@Mango.Services.ProductAPI_HostAddress = https://localhost:7000

GET {{Mango.Services.ProductAPI_HostAddress}}/api/product

###

@id=1
GET {{Mango.Services.ProductAPI_HostAddress}}/api/product/{{id}}

###
